name: gherkin
version: 1.1.9
description: A Gherkin parsers and runner for Dart which is very similar to Cucumber, it provides the base BDD functionality ready for use in platform specific implementations i.e. flutter/web
homepage: https://github.com/jonsamwell/dart_gherkin

dependencies:
  glob: ">=1.1.7 <2.0.0"
  path: ">=1.6.2 <2.0.0"
  test: ">=1.6.1 <2.0.0"
  matcher: ">=0.12.5 <1.0.0"

dev_dependencies:
  pedantic: ">=1.5.0 <2.0.0"

environment:
  sdk: ">=2.6.0 <3.0.0"
